1. Required Fields

BOT_TOKEN: 
GDRIVE_FOLDER_ID: 
OWNER_ID: 1441767180 
DOWNLOAD_DIR: 
DOWNLOAD_STATUS_UPDATE_INTERVAL:
AUTO_DELETE_MESSAGE_DURATION: 
IS_TEAM_DRIVE: 
TELEGRAM_API: 7763257
TELEGRAM_HASH: 52c9cbf4b4ee78eda09eb3d9ac0673d7

DATABASE_URL: 
AUTHORIZED_CHATS: 
SUDO_USERS: 1441767180 
IGNORE_PENDING_REQUESTS: True 
USE_SERVICE_ACCOUNTS: 
INDEX_URL: 
STATUS_LIMIT: 
STOP_DUPLICATE: 
CMD_INDEX: 
UPTOBOX_TOKEN: 
TORRENT_TIMEOUT: 
EXTENTION_FILTER: 
INCOMPLETE_TASK_NOTIFIER: 
Update
UPSTREAM_REPO: 
UPSTREAM_BRANCH:
AUTO_MUTE: 
CHAT_ID: 
FSUB: 
CHANNEL_USERNAME: 
FSUB_CHANNEL_ID: 
